// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsgeoqroutrrhbxnkats.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZ2VvcXJvdXRycmhieG5rYXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDMzMTYsImV4cCI6MjA2NDI3OTMxNn0.iHGEa98Ib4EP2zFGd4hcNtWyJj3VyDF3G9jsrH4gxc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);